# Generated by Django 3.1.7 on 2021-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_events_gallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadharno',
            field=models.CharField(max_length=12, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=120),
        ),
    ]
