# Generated by Django 3.1.7 on 2021-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210702_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=25, null='True'),
            preserve_default='True',
        ),
    ]
