# Generated by Django 3.1.7 on 2021-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_user_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nm',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
    ]
