# Generated by Django 3.1.7 on 2021-07-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_user_fnm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fnm',
            new_name='fathernm',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='occupation',
            new_name='fatheroccupation',
        ),
    ]
