# Generated by Django 3.1.7 on 2021-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20210706_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fathernm',
            new_name='fathername',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nm',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null='True'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null='True'),
        ),
    ]
