# Generated by Django 3.1.7 on 2021-07-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20210706_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
                ('fathername', models.CharField(max_length=50, null='True')),
                ('fatheroccupation', models.CharField(max_length=25, null='True')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10)),
                ('age', models.IntegerField(default=10)),
                ('aadharno', models.CharField(max_length=12, null='True')),
                ('phno', models.CharField(max_length=30, null='True')),
                ('address', models.TextField(null='True')),
                ('city', models.CharField(max_length=30, null='True')),
                ('state', models.CharField(max_length=40, null='True')),
                ('pin', models.IntegerField(null='True')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='aadharno',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fatheroccupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
