# Generated by Django 3.1.7 on 2021-07-10 04:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20210706_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
