# Generated by Django 3.1.7 on 2021-07-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_form_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='avatar',
        ),
    ]
