# Generated by Django 3.1.7 on 2021-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='profiles/'),
        ),
    ]
