# Generated by Django 3.1.7 on 2021-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_dash'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='study',
            field=models.CharField(choices=[('i', 'illiterate'), ('s', 'Below 7th'), ('t', '10th'), ('B', 'Above 10th'), ('t', 'Above 12th'), ('o', 'Higher Studies')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not say')], default='M', max_length=10),
        ),
    ]
