# Generated by Django 3.1.7 on 2021-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20210713_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='study',
            field=models.CharField(choices=[('i', 'illiterate'), ('s', 'Below 7th'), ('t', '10th'), ('B', 'Above 10th'), ('o', 'Higher Studies')], default='s', max_length=10),
        ),
    ]
