# Generated by Django 3.1.7 on 2021-07-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20210713_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=120)),
                ('image', models.ImageField(default='profile.jpg', upload_to='profiles/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not say')], default='M', max_length=10)),
                ('aadharno', models.CharField(max_length=12, null='True')),
                ('phno', models.CharField(max_length=30, null='True')),
                ('address', models.TextField(null='True')),
                ('city', models.CharField(max_length=30, null='True')),
                ('state', models.CharField(max_length=40, null='True')),
                ('pin', models.IntegerField(null='True')),
            ],
        ),
    ]
