# Generated by Django 3.1.7 on 2021-07-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
