# Generated by Django 3.1.7 on 2021-07-15 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_auto_20210715_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='aadharno',
        ),
        migrations.RemoveField(
            model_name='work',
            name='address',
        ),
        migrations.RemoveField(
            model_name='work',
            name='age',
        ),
        migrations.RemoveField(
            model_name='work',
            name='city',
        ),
        migrations.RemoveField(
            model_name='work',
            name='email',
        ),
        migrations.RemoveField(
            model_name='work',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='work',
            name='image',
        ),
        migrations.RemoveField(
            model_name='work',
            name='phno',
        ),
        migrations.RemoveField(
            model_name='work',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='work',
            name='state',
        ),
        migrations.AddField(
            model_name='work',
            name='des',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='pics'),
            preserve_default=False,
        ),
    ]
