# Generated by Django 3.1.7 on 2021-07-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_auto_20210715_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='addres',
            new_name='address',
        ),
        migrations.AddField(
            model_name='work',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not say')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='work',
            name='qualification',
            field=models.CharField(choices=[('M', 'Manager'), ('W', 'Workers'), ('A', 'Ass.Manager'), ('s', 'Suppoters'), ('o', 'Others')], default='M', max_length=10),
        ),
    ]
